<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>ShineMung.SM001</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <StartupObject>ThreeScreen.Program</StartupObject>
    <EdsdkSourcePath>C:\GitHub\EDSDK_64\Dll</EdsdkSourcePath>
  </PropertyGroup>
  <ItemGroup>
    <None Update="assets\backgrounds\*.png" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="lib\EDSDK\x64\*.dll" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" Link="%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
